/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

public class App {

    public static void main(String[] args) {
        System.out.println(section1());
        System.out.println(section2());
        System.out.println(section3());
        System.out.println(section4());
    }

    public static String section1() {
        // Write section 1 code here

        // Hint: How to return the values as a string
//        return "num: " + num + "\n" +
//                "average: " + average + "\n" +
//                "letter: " + letter + "\n" +
//                "isTrue: " + isTrue + "\n";
    }

    public static String section2() {
        // Write section 2 code here
    }

    public static String section3() {
        // Write section 3 code here
    }

    public static String section4() {
        // Write section 4 code here
    }

}
